### ISSUE TITLE
Broken links on main page

### ISSUE THREAD

**Issue by Blucky87** [prime31/Nez#101]
The links on the main github page are broken.

![capture](https://cloud.githubusercontent.com/assets/3120102/17846820/ad81e96a-6818-11e6-8cb1-7ea5eefacc14.PNG)

**Comment by prime31** [comment]
all fixed

**Comment by piedoom** [comment]
Just a note - 
because gh-pages uses Jekyll, when building the [docs](http://prime31.github.io/Nez/documentation/setup/installation) site, I was unable to dynamically link to the .md files from the FAQs folder.  This means there is a duplicate of the FAQs in the [gh-pages branch](https://github.com/prime31/Nez/tree/gh-pages/documentation/systems).  It's of course up to you on where documentation should be held, but it might be difficult to keep 2 branches in sync with each other.

**Comment by prime31** [comment]
My plan was to keep them all duplicated for a bit then phase out the md files once folks get used to the new location.
