### ISSUE TITLE
Debug lines are not drawn in screen space

### ISSUE THREAD

**Issue by ThomasZeman** [prime31/Nez#130]
When using a high "defaultDesignResolution" like e.g. 4000x3000pxs and e.g. SceneResolutionPolicy.ShowAll debug lines (like for example for colliders) are drawn in the design resolution and therefore hardly visible (or only with aliasing artifacts) in the final output.

**Comment by prime31** [comment]
I am thinking the best/easiest solution for this would be to make the debug like size configurable. That should cover all current and future resolutions.

**Comment by ThomasZeman** [comment]
Definately easiest. Bit more spohisticated would be to transform the polygon/line points into screen space and just draw it there with 1px width.

**Comment by prime31** [comment]
That could work as well though it would require a different underlying debug draw strategy. Currently Renderers decide what to debug render and they could be doing all kinds of transformed shenanigans in different render targets with different cameras. Getting back to screen space could be tricky. Good for a future consideration when a debug rewrite happens for sure but not easy to squeeze into the current system.

**Comment by prime31** [comment]
Hmm. Now that I think about it that might actually be possible to do right now sanely. The Viewport will always be set to the RenderTarget size and that can be used along with the actual device back buffer size to determine what an actual pixel would be in the current RenderTarget.

Render to 4000x2000 RT with an actual back buffer size of 2000x1000:
- (width should work fine to get a differential to work with)
- 4000 / 2000 = 2px in render space to get 1px in back buffer space

This breaks down when rendering to an RT smaller than the back buffer though since we cant render less than a pixel. That can be easily solved by maxing with 1.

Render to 400x200 RT with an actual back buffer size of 2000x1000:
- 400 / 2000 = 0.2px in render space to get 1px in back buffer space

**Comment by ThomasZeman** [comment]
Yes, sure!
