### ISSUE TITLE
Bidirectional dependency in RenderableComponent causes infinite loop if not overridden

### ISSUE THREAD

**Issue by Vanit** [prime31/Nez#147]
Found this little gem while writing my own renderable component. Seems like the only reason this isn't normally an issue is that the stock Nez renderable components always break the loop by overriding width/height or bounds. I'm not sure what the best way to resolve this is without affecting dependencies that rely on either field to depend on the other.

		/// <summary>
		/// width of the RenderableComponent. subclasses that do not override the bounds property must implement this!
		/// </summary>
		/// <value>The width.</value>
		public virtual float width { get { return bounds.width; } }

		/// <summary>
		/// height of the RenderableComponent. subclasses that do not override the bounds property must implement this!
		/// </summary>
		/// <value>The height.</value>
		public virtual float height { get { return bounds.height; } }

		/// <summary>
		/// the AABB that wraps this object. Used for camera culling.
		/// </summary>
		/// <value>The bounds.</value>
		public virtual RectangleF bounds
		{
			get
			{
				if( _areBoundsDirty )
				{
					_bounds.calculateBounds( entity.transform.position, _localOffset, Vector2.Zero, entity.transform.scale, entity.transform.rotation, width, height );
					_areBoundsDirty = false;
				}

				return _bounds;
			}
		}

**Comment by prime31** [comment]
That is by design. If you don't override either width/height or bounds culling breaks so the infinite loop is an indicator. Not the most fantastic of indicators but at least you find out quick when you do something wrong.

There is a stearn warning in the class comments at the top of the file which is (hopefully) there to lead you quickly to the solution.

    	Subclasses MUST either override width/height or bounds!

A more elegant solution might be to reflect all three properties at runtime and make sure they are overridden correctly. Perhaps doing that in the constructor could work since it is way, way too slow to do every time they are accessed.

**Comment by Vanit** [comment]
Blargh, I see the comments now, they're even in the snippet I provided. Clearly the issue lies with my tendency to skim over documentation. =/

Thanks for the swift reply!
