### ISSUE TITLE
Why camelCase?

### ISSUE THREAD

**Issue by witlock** [prime31/Nez#15]

**Comment by prime31** [comment]
I dislike pressing the shift key for no good reason. And all the other reasons why someone would choose camel case.

**Comment by cra0zy** [comment]
@prime31 Just a recommendation, follow Microsoft's C# guidelines for C# library...

What you are doing right now is just like using PascalCase in Java... it just doesn't go well with the rest of the code.

Also, on a side note, whenever I code in Java, I use camelCase, whenever I code in C# I use PascalCase (talking about public stuff of course).

**Comment by prime31** [comment]
@cra0zy, I've never been much of a follower of convention. If a coding style makes sense to me (as camelCase does) then I don't see any reason not to use it. Most IDEs have one click refactoring including code styles so if your preference differs by all means switch it over. We all have our own preferences!

**Comment by cra0zy** [comment]
You and I are very different when it comes to programming, you seem to be keeping the same coding style for all the programming languages, while I switch between them depending on the language.

**Comment by prime31** [comment]
Indeed. We are all different and have our own unique preferences. For me, the readability and unambiguity of not having capitalized methods and properties outweighs the benefit of following along with the pack. For you that is not the case. Neither are correct, neither are wrong.

**Comment by witlock** [comment]
The problem with all this is that it forces everyone to switch while using this library and it's going to be a drag to use combine it with other languages, because it's one of the few using camelCase.
I definitely understand why you want to keep doing what you are doing though.
Sadly this is the only reason why I decided not to use Nez.

PS: I also use different coding styles for different languages.

**Comment by cra0zy** [comment]
> The problem with all this is that it forces everyone to switch while using this library and it's going to be a drag to use combine it with other languages, because it's one of the few using camelCase.
> I definitely understand why you want to keep doing what you are doing though.
> Sadly this is the only reason why I decided not to use Nez.

:+1:

**Comment by gregkrsak** [comment]
You're kidding me right? Speaking as a dev with startup and gaming industry
experience, the answer is 1. You use the standard that the project you're
working on uses, and 2. You don't complain about it.

You certainly don't bail just because you can't handle it. That wouldn't
fly in the professional world.

If the project owner wants to use screaming snake case, who cares? Man up
and make your code look like the rest of the existing code. It's what
professionals do.

You should be thankful for the open source experience.

And you should wrap your external libraries anyway.

**Comment by cra0zy** [comment]
@gregkrsak So... you would prefer that everyone code in a way that makes sense to them as opposed to code in a way that is standard for the specified programming language?

**Comment by gregkrsak** [comment]
Make your code beautiful. Make it clear to someone who unearths it 10 years
from now; don't be afraid to comment a lot, to that end. Be an artist, not
an engineer.

That's the highest coding standard.

If an existing style guide fulfills that high standard, by all means use
it. If not, don't.

**Comment by prime31** [comment]
@gregkrsak spot on. My thoughts exactly. If the code is clean, consistent and well commented that is way more important than some silly style choice.

@witlock, if a capital letter is what keeps you from using Nez I feel sorry for you. You are missing out on a fun little library just because you like to press your shift key excessively ;) At the least I would suggest grabbing some of the parts that you want for your game and just smacking them with Resharper to make them whatever style you like so that you can take advantage of all the open source code here.

**Comment by cra0zy** [comment]
Just gonna mention, I don't use shift ever.... I use caps lock....

**Comment by craftworkgames** [comment]
> I dislike pressing the shift key for no good reason. And all the other reasons why someone would choose camel case.

> someone who unearths it 10 years from now

> just because you like to press your shift key excessively ;)

> I don't use shift ever for big letters.... I use caps lock....

`iJustGottaSayThisIsOneOfTheFunniestArgumentsIHaveSeenOnTheInternets.Seriously();`

**Comment by prime31** [comment]
@craftworkgames, didn't you mean IJustGottaSayThisIsOneOfTheFunniestArgumentsIHaveSeenOnTheInternets.Seriously() (capital I to start it off ;)

**Comment by Async0x42** [comment]
To be honest, I'm just happy everything isn't prefixed with an m / m_ or similar! Capitals or lack-of are easily dealt if you've got any kind of Intellisense.

Regardless, I'm really grateful for the work you've put into this library @prime31, it's just a hobby of mine, but this is a really top-notch framework to use with MonoGame (and even just to study)

**Comment by prime31** [comment]
I was *just* about to start adding m_ to everything. Including methods, class names and file names ;)

Glad to hear you are liking Nez!

**Comment by witlock** [comment]
@prime31 I really like what Nez has going on and I'm planning on using certain parts of it. I really tried to go along with the style, but I just couldn't. I totally forgot what my best friend ReSharper can do for me though!
