### ISSUE TITLE
Dranw count method not found. with recent version of monogame

### ISSUE THREAD

**Issue by gillesboisson** [prime31/Nez#151]
Hi,

I update monogame by mistake (3.6.0.1187), and I have issue when exec a nez project (last version). Here is the error "Microsoft.Xna.Framework.Graphics.GraphicsMetrics.get_DrawCount" throwed on Game.Run() method.

I didn't find a way to go back to the version of monogame Nez use (3.6.0.121 based on Monogame PCL included in Nez-portable). Is there any way to get all platform assemblies for this specific version. I tried to recompile from monogame sources but it just didn't work.

Thanks guys,

**Comment by prime31** [comment]
3.6 is not yet released so the Nez repo is not compatible with it. From what I understand DrawCount was removed in MG 3.6 so you'll have to comment out the code that accesses it in Nez if you are using 3.6. If you use any Nez shaders they will need to be recompiled against 3.6 as well due to the changes present.

**Comment by gillesboisson** [comment]
Thanks, I switch back to monogame 3.5 and nez 0.9, it works perfectly now
