### ISSUE TITLE
Texture Packer atlas import error

### ISSUE THREAD

**Issue by Blucky87** [prime31/Nez#17]
When importing a texture packer atlas, the only way to get it to work is to have the  json file named something like "texturepacker.json" and have the png with the sprites "texturepacker_atlas.png" and in the file "TexturePackerAtlasReader.cs" Line 13 needs to be `var texture = reader.ContentManager.Load<Texture2D>( assetName + "_atlas");`  If you do not add the _atlas, calling `myScene.contentManager.Load<TexturePackerAtlas>("texturepacker")` will return a texture2D

**Comment by prime31** [comment]
Your image file does indeed need to be named something different than your json file. There is no need to modify the the importer itself though. You can just change the "image" metadata to be the image name and ensure it is different than the json file name. This is currently a limitation of MonoGame in that ever file that goes through the Pipeline tool has to have a different name since they all get the xnb file extension.
