### ISSUE TITLE
Scene transitions potentially broken

### ISSUE THREAD

**Issue by parkersprouse** [prime31/Nez#176]
I'm using MonoGame version 3.6.1236 and Nez at commit d2d6844.

I have all of the effects and transitions that come with Nez in the `Content/nez` folder and they're all set to build as content and get copied over. When I try to transition from one scene to another using the line `Core.startSceneTransition(new WindTransition(() => new LevelScene(LevelName.Begin)));`, it throws the following exception:
```
Exception thrown: 'System.Reflection.TargetInvocationException' in mscorlib.dll
The program '[59368] MyGame.vshost.exe' has exited with code -1073741510 (0xc000013a).
```
Then the file `NezContentManager.cs` opens up at line [90](https://github.com/prime31/Nez/blob/master/Nez.Portable/Utils/NezContentManager.cs#L90), which is `var effect = Activator.CreateInstance(typeof(T), Core.graphicsDevice, effectCode) as T;`

I was able to use them in the past for a different project, so I'm not sure what the issue could be.

**Comment by prime31** [comment]
Nez doesn't have any official support for MonoGame 3.6 seeing as how 3.6 isn't yet released. This particular issue sure does sound like it is due to the 3.6 shader changes. If you want to dig in further I'd recommend just setting a breakpoint and walking through the constructor to see where the issue is. If I had to guess the MonoGame Effect constructor loading the new effect file format is most likely the cause.
