### ISSUE TITLE
Adding a pause menu

### ISSUE THREAD

**Issue by qntf** [prime31/Nez#267]
What's the best way to implement a semi-transparent pause menu (like an overlay,) using Nez?
I want to have the overlay show up and pause updating the scene behind, and I want it
to have some transparency. The pause overlay should also support UI elements.

What is the best way to implement something like this?

**Comment by Romans-I-XVI** [comment]
This isn't really Nez specific but it seems there are a couple ways to implement this in general. You obviously won't be able to stop updating entirely because you need components that aren't paused in order to resume gameplay and interact with the overlay. 

The way I do it in my engine is anything that's updatable has a variable to declare whether it's pausable. If the game is declared to be paused and an object is pausable  the update code won't be run. Then other objects can be declared as not pausable and they will always be processed like normal regardless of if the game is paused. 

You could either implement this throughout your game on each individual object or implement it at the engine level. Which is easier probably depends on the size of your game. 

Again this is not Nez specific and I don't know enough about Nez to know how to implement it at the engine level. But since nobody has answered the question yet I figured I'd share how you could possibly accomplish what you want. 

or... If you want to go straight hackish you could take a screenshot of the current scene, switch to a pause scene and draw the screenshot you took underneath, then switch back to the gameplay scene and delete the screenshot 😄

**Comment by qntf** [comment]
Thanks!

How would I do something like adding a semi-transparent overlay in the background and a UI that only shows up in the pause state?

**Comment by prime31** [comment]
Closing out all old Nez bugs without recent activity. If you are still seeing any issues feel free to open a new bug and include a full repro project that clearly shows the issue.
