### ISSUE TITLE
Clarification of game physics?

### ISSUE THREAD

**Issue by dsaf** [prime31/Nez#278]
@prime31 I have a few questions after reading the [Physics FAQ](https://github.com/prime31/Nez/blob/master/FAQs/Physics.md) that might be useful for other people as well. I understand if you don't have time to explain, but even "yes/no" answers would be helpful.

1) Is "game physics" effectively like "realistic physics" but without (predetermined) collision response?
2) Does "game physics" deliberately omit angles and angular movement (unless I misunderstood the code)?
3) Does "game physics" assume low velocities to avoid tunnelling?
4) What happens if "too much" time passes between Update calls (for whatever rare reason) - is tunneling also possible in such case?
5) Is [Nez.PhysicsShapes.BETA.RealtimeCollisions](https://github.com/prime31/Nez/blob/master/Nez.Portable/Physics/Shapes/RealtimeCollisions.cs) an early prototype of continous collision detection?

**Comment by dsaf** [comment]
I have just seen https://github.com/prime31/Nez/issues/8 but some confirmation of my thoughts would still be appreciated.

**Comment by Alan-FGR** [comment]
I'm no Nez expert, but lemme try and help you a bit:
> Is "game physics" effectively like "realistic physics" but without (predetermined) collision response?

"Nez Physics" is intended mainly for collision detection afaik, it's useful if you want to move stuff manually and just need a way to efficiently check overlapping shapes to know what is colliding. It's by no means a physics system.
> Does "game physics" deliberately omit angles and angular movement (unless I misunderstood the code)?

I could be wrong here, but I guess you're right. If you want stuff like angular momentum, you'd have to keep track of that separately, and obviously get contacts and do a bit of trig to apply angular accelerations and etc, but at this point I'd definitely checking if it wouldn't be better to simply use Farseer.
> Does "game physics" assume low velocities to avoid tunnelling?

I think it's pretty safe to say that it assumes your highest speed object can't travel a distance that's bigger than your thinnest 'wall' between two ticks.
> What happens if "too much" time passes between Update calls (for whatever rare reason) - is tunneling also possible in such case?

Definitely. If that's a problem you may want to remedy that by manually sweep checking in these situations. Ideally collision checking shouldn't be framerate dependent.

**Comment by dsaf** [comment]
@Alan-FGR Thank you for confirming my thoughts. I am trying to stay away from Farseer/Box2D.

> Ideally collision checking shouldn't be framerate dependent.

That won't help if ```Draw()```-independent ```Update()``` just starts taking too much time to complete every cycle though?

**Comment by Alan-FGR** [comment]
@dsaf well, if the hardware cannot process it at an acceptable frequency, you have basically two options: increase the time delta you use in your physics/simulation, what could cause all kinds of problems as tunneling, but depending on the game could be acceptable if you sweep-test objects when they may potentially tunnel through stuff. Another option is just to simply let the physics slow it down, and if the rendering takes considerable resources, skipping frames from rendering may help process it faster, but this is only helpful if you're dealing with a spike in processing, what may happen when many objects are in contact simultaneously. In some games that's not acceptable, and although this last option is the 'default' in modern engines, it's only useful as a way to gracefully degrade the experience if you ever have a situation where the physics bottlenecks it, what should be extremely rare.

While I'm also not a fan of using fully-featured physics engine for games unless absolutely necessary, if performance is a concern, rest assured they are well-optimize to handle most scenarios, probably much better than what you'll achieve with a naive/brute force approach, especially if the number of bodies and contacts/impulses is high because they have contact persistence and other non-trivial optimizations.

There are other tricks you could also try in order to deal with performance problems, but they're generally very specific; for example, I once optimized a game that was generating a lot of contacts (and ticked the physics at every render frame, what's not recommended) simply by passing a larger timestep to the physics but limiting changes in position, so in that specific game it was a huge improvement because it prevented the objects from generating more contacts excessively, what was causing the slow downs.

I think the "Nez Physics" isn't really intended for games with a massive number of collisions, it's more useful for games where the physics are so fast to process that you could just do that at every render frame and it won't matter much really, and if you were GPU-bound you could simply sub-step it. If your game is going to be CPU-bound and you think collision detection or physics simulation are going to be bottlenecks, you may need a custom solution, maybe binding a fast native library. I have wrapped Chipmunk in a buffered system with great success to use from C# (by pinvoking). Unfortunately it's not open source, but it isn't hard to do that, just assemble command buffers and pass them around, in C# you can take advantage of the thread-safe collections to add commands easily to a buffer from multiple threads, and on the unmanaged side Chipmunk has a multi-threaded solver that's very fast for massive simulations with a reasonable quality (iters). It uses pthreads though, so for Win32 you'll have a bit of work to get it running, but I successfully used [this](https://sourceware.org/pthreads-win32/), and there's also a PR on the official repo that implements a minimal pthreads version, but you may want to benchmark it to make sure it's as fast as that implementation I just linked.

**Comment by dsaf** [comment]
@Alan-FGR There is a lot of food for thought in your answer for me - thank you!

**Comment by Vanit** [comment]
I think we can call this closed :)
