### ISSUE TITLE
setDesignResolution causes UI to render incorrectly

### ISSUE THREAD

**Issue by phxvyper** [prime31/Nez#304]
I have the following UI just to get things rolling:

```cs
private void SetupMenu()
{
    var ui = camera.addComponent(new UICanvas());
    ui.isFullScreen = true;

    var skin = Skin.createDefaultSkin();
    var table = ui.stage.addElement(new Table());
            
    table.setFillParent(true).center();

    var playTestButton = table.add(new TextButton("Play Test Level", skin)).setFillX().setMinHeight(30).getElement<TextButton>();
    playTestButton.onClicked += b =>
    {
        Game.scene = new PlayerTestScene();
    };

    table.row().setPadTop(15f);

    var exitButton = table.add(new TextButton("Exit", skin)).setFillX().setMinHeight(30).getElement<TextButton>();
    exitButton.onClicked += b =>
    {
        Game.exit();
    };
}
```

Any translation I make to the camera isn't retained by the UI, so setting the position of the camera to (200, 200) would put the UI more towards the top left of the screen space. Even if I set the position of the UI's entity, there is no change in its rendered position.

How do I make the UICanvas component's rendered stage stay relative to my camera's position **while using a design resolution**, i.e retain camera space rendering?

**Comment by phxvyper** [comment]
We actually managed to fix the issue with the UI not moving relative to the camera using the `ScreenSpaceRenderer`. However, we're having an issue when using `setDesignResolution`.

This is what the UI displays as without a design resolution:

![](https://i.imgur.com/BzBnidW.png)

This is what the UI displays as with a design resolution. The buttons act as if they're in the center of the screen, and they are not rendered where they should be. (they highlight and are clickable in the center of the screen, and not where they're rendered):

![](https://i.imgur.com/rT7OMqm.png)

Why do design resolutions cause this weird behaviour and how can I prevent it from happening **while still maintaining a design resolution**?

**Comment by phxvyper** [comment]
@prime31 Still unsure about this issue. I'm somewhat dependent upon `setDesignResolution` to ensure a certain screen size is met, but this issue is still prevalent.

**Comment by Vanit** [comment]
I believe I've found the source of the bug, though I'm not sure what the correct fix is. The give away is if you resize the window smaller with table debugging turned on:

![table_design_debug](https://user-images.githubusercontent.com/852857/35478447-973fb8e0-0429-11e8-9262-0fa108959ac0.png)

I can confirm the scaled size of the screen is correctly propagating down the UI stack (and you can see in the screenshot that the table appears to be the right size, just in the wrong position). From what I can tell it looks like the design size is incorrectly being passed to **camera.onSceneRenderTargetSizeChanged( renderTargetWidth, renderTargetHeight )** instead of the scaled sized, which is causing the camera to appear incorrectly offset.

Comments @prime31?

**Comment by Vanit** [comment]
After a lot of digging I believe this is working as intended; you're just not supposed to set `isFullScreen = true` while using `setDesignResolution()`. Leaving isFullScreen off fixes the issue.

I believe this can be closed.

**Comment by phxvyper** [comment]
Since the priority for the project I was working on was lowered, I'll go ahead and close this without testing it out. If it ends up continuing to be an issue ill reopen or make another issue.

**Comment by Vanit** [comment]
All good, I just wanted to get a resolution in here for future reference :)
