### ISSUE TITLE
Cannot use pipeline importers

### ISSUE THREAD

**Issue by lmerotta** [prime31/Nez#40]
I am pretty new to Nez (and Monogame in general), and am trying to add the project inside Nez.PipelineImporter to my solution, which already references the Nez-PCL project.

I can add the  Nez-PipelineImporter project correctly, but on compile time my IDE says that it is missing a reference for "Microsoft.Xna.Framework.Content.Pipeline;". There is unfortunately no documentation on how to add the PipelineImporter project.

Any help is greatly appreciated !

**Comment by ranrez** [comment]
I've been fighting getting the Pipeline importer to work just now and was able to get past a similar error to what you're seeing. I say similar because for me it was failing to find references to "Monogame.Framework.Content.Pipeline" instead of the XNA reference. Either way, I'll explain below how I restored all of the references. Hopefully this will apply to you too. 

Problem: NuGet (a package manager integrated into VS) is not actually downloading the needed dependencies/references (even though it says it is)

Solution:

1. Ensure the Nez.PipelineImporter is selected in the Solution Explorer

2. Click on TOOLS -> NuGet Package Manager -> Package Manager Console

3. In the console window, run this: Update-Package -Reinstall -Safe

4. Attempt a build and see if it cleared the error. 

I should warn you, even if you get past that reference errors, the PipelineImporter still doesn't build due to some coding errors (at least for me).

**Comment by prime31** [comment]
@ranrez what errors are you seeing in the Nez.PipelineImporter project when building? I use it every day and have no issues at all with errors in the project..

**Comment by lmerotta** [comment]
@ranrez dude, you made my day ! Everything is working fine now !
@prime31 should I create a PR to add this in the docs ?

**Comment by ranrez** [comment]
@prime31 

This is what I'm getting now. A whole bunch of errors like this:

"Error 1 'Nez.BitmapFontImporter.BitmapFontProcessor.packTexturesIntoXnb.get' must declare a body because it is not marked abstract, extern, or partial BitmapFontProcessor.cs 17 43	Nez.PipelineImporter

I'm using Visual Studios 2013, Monogame 3.5

**Comment by prime31** [comment]
@lmerotta it cant hurt to have an extra note in the docs. Feel free to send a PR over.

@ranrez Nez has a tiny amount of C# 6 code. That is what you are seeing with that error. Just set Visual Studio to use the latest .NET profile and it should clear that up (assuming VS 2013 supports C# 6. I havent used it in years so I have no idea if it does).
