### ISSUE TITLE
FollowCamera seems to have lag problem.

### ISSUE THREAD

**Issue by MrTambourineSLO** [prime31/Nez#442]
When using a FollowCamera in nez it seems to have a noticable sttuter / lag when following the entity (in Ninja Adventure scene in samples that's obviously player entity).
See video below:
[Nez follow camera lag](https://youtu.be/h-YElwW2Re4)  
I have tried replicating this bug in side scrolling experiment and it was easily reproduced:
See video:
[Nez follow camera lag 2](https://youtu.be/eq5LaHTkVbY)  
Source code:  
[Nez squirrel on bitbucket](https://bitbucket.org/saso_miocinovic/nezsquirrel/src/origin/)

**Comment by prime31** [comment]
The demos are not meant to be full, complex implementations. They are purposely made as simple as possible so beginners can pick them apart straight away. When dealing with low res pixel art you will want to implement subpixel movement to avoid the rounding and jitter that occurs without it.

**Comment by MrTambourineSLO** [comment]
Will check, thanks a bunch!

**Comment by nickcacace** [comment]
Even with the SubpixelVector2 code included in the Ninja scene, the ninja adventure still experiences the jittering shown in the above videos.

**Comment by prime31** [comment]
Set your timestep to fixed. Note also previous comment:

> The demos are not meant to be full, complex implementations. They are purposely made as simple as possible so beginners can pick them apart straight away. When dealing with low res pixel art you will want to implement subpixel movement to avoid the rounding and jitter that occurs without it.

**Comment by MrTambourineSLO** [comment]
If you have a potato computer I also suggest limiting framerate to 30 down from 60 and turning vsync off...

**Comment by Gavolot** [comment]
None of this just works. I've tried both limiting the frequency and turning off Vsync.

I've tried literally all of it. Either the camera itself is shaking, or some kind of float noise. I don't understand how you can work with this at all =)

It's funny when you make 20 variations. And the pure implementation of the camera for a mono game works the first time.

**Comment by nickcacace** [comment]
> 
> 
> None of this just works. I've tried both limiting the frequency and turning off Vsync.
>

When I was first looking into Nez, I found this issue present in the demos even when using the SubpixelVector2 as mentioned above.

From what I remember this problem was due to the way that Nez draws/calculates low res pixel art games. In my own project my solution around this was to draw in my native resolution (240x135) and scale it up on the GPU to a more usable resolution like 1080x1920 for fairly little cost.

I'm not sure how you'd implement this in Nez anymore. I moved on to my own stuff after this exchange left a sour taste in my mouth. I understand that the demos aren't full implementations, but you'd think they would at least be free of what I would call major graphical errors. I suspect Nez just isn't used very often for low resolution pixel art games.
