### ISSUE TITLE
Nez / FNA / ImGUI breaks on ImGui intialization

### ISSUE THREAD

**Issue by hotdiggitydoddo** [prime31/Nez#461]
Following the instructions to the tee on the ReadMe on getting Nez to play nice with FNA, when I add the ImGUI project and try to instantiate the ImGuiManager, the following exception gets thrown:

![image](https://user-images.githubusercontent.com/2938036/55680201-6c4b7280-58cb-11e9-8558-a93a09ca60ca.png)

This happens only on Windows platform.

**Comment by CountessAnise** [comment]
You are correct. I'm not sure why this doesn't happen on different platforms but unfortunately this API doesn't take generics types (even on CoreCLR).  
[.NET Framework](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getfunctionpointerfordelegate?view=netframework-4.7.2) and [.NET Core](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getfunctionpointerfordelegate?view=netcore-2.2) documentation links.  
Although poorly documented, it's listed as a possible exception:

```
Exceptions
ArgumentException
The d parameter is a generic type definition.
```

The API is also marked as obsolete.  
So a better way to do this would be to use the non-obsolete API with an actual `delegate` and no reflection.


We can add the delegates to the `#if FNA` preprocessor directives (right above the `void setupInput()` method where the exception occurs)
```csharp
#if FNA
        private delegate void setClipboardTextDelegate(IntPtr userData, string txt);
        private delegate string getClipboardTextDelegate();

        static void setClipboardText( IntPtr userData, string txt )
		{
			SDL2.SDL.SDL_SetClipboardText( txt );
		}
#endif

```

And instead of:
```csharp
#if FNA
			// forward clipboard methods to SDL
			var setClipboardMethod = GetType().GetMethod( "setClipboardText", System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.NonPublic );
			io.SetClipboardTextFn = Marshal.GetFunctionPointerForDelegate( Delegate.CreateDelegate( typeof( Action<IntPtr,string> ), null, setClipboardMethod ) );

			var getClipMethod = typeof( SDL2.SDL ).GetMethod( "SDL_GetClipboardText" );
			io.GetClipboardTextFn = Marshal.GetFunctionPointerForDelegate( Delegate.CreateDelegate( typeof( Func<string> ), null, getClipMethod ) );
#endif
```
We can do:
```csharp
#if FNA
			// forward clipboard methods to SDL
            io.SetClipboardTextFn = Marshal.GetFunctionPointerForDelegate<setClipboardTextDelegate>(setClipboardText);
            io.GetClipboardTextFn = Marshal.GetFunctionPointerForDelegate<getClipboardTextDelegate>(SDL2.SDL.SDL_GetClipboardText);
#endif

```

This works.

**Comment by prime31** [comment]
That is more or less exactly the code I have in my dotnet Core 3 branch. I'll push it to master now.
