### ISSUE TITLE
.Net Core support?

### ISSUE THREAD

**Issue by hammackj** [prime31/Nez#479]
Is it possible to get this running with cra0zy's .netcore build of Monogame?

**Comment by prime31** [comment]
Nez is a PCL so it already complies to net standard. You can find an example of an FNA dotnet core csproj file [here](https://github.com/prime31/Nez/blob/master/Nez.Portable/Nez.FNA.Standard.csproj).  A MonoGame version should be nearly identical.

**Comment by hammackj** [comment]
Thanks I was able to get it to compile for core. I had some issues with the pipeline framework compiling under core, I couldn't find the right library on the core side for that. I switched back to normal Mono for now. Cool framework, thanks!

**Comment by nikarh** [comment]
Sorry for resurrecting the old issue, I have noticed that there the only netcore .csproj files is for FNA and just in Nez.Portable subproject. Do you mind if I do a PR with csproj files for ImGui, Persistence and FarseerPhysics for netcore & FNA? Also, is there a particular reason why you have created separate .csproj files for netcore and .net framework, instead of creating a multiframework build file? Thanks!
