### ISSUE TITLE
Update Tmx specs to the latest (0.15+)

### ISSUE THREAD

**Issue by Async0x42** [prime31/Nez#6]
There's actually a number of new map changes since the 0.11, such as 

- offsetX/Y for object groups, layers, image layers, tileset columns and counts
-  x/y in image layer has been depreciated, etc.

Per the documentation @ http://doc.mapeditor.org/reference/tmx-map-format/ (the relevant lines will say '(since 0.13)' or '(since 0.15), changelog for TMX format is here: http://doc.mapeditor.org/reference/tmx-changelog/

**Comment by Trebor777** [comment]
Also, External tilesets (.tsx) files for maps are not supported. :) Currently we can't build maps with using those, and the pipeline doesn't know what to do with them.

**Comment by prime31** [comment]
Pull requests are always welcome!

**Comment by Async0x42** [comment]
I haven't switched over my older projects to Nez yet, but once I get everything settled then I'll see about helping out with various improvements to Tiled, I'm just kind of time limited right now so am posting all my suggestions!

**Comment by Trebor777** [comment]
I'm really sorry, I should double check when I post stuff :p This being quite in the early stages I thought it would be a code issue ahah... but no, it's my data. External tilsets works (as in the map builds correctly in the pipeline) hence why there is no importer for the actual tilesets files (I think). My path was badly set in some of them...

**Comment by Trebor777** [comment]
I'm working on something :) 
I trying to fix 2 things: 
-> Getting the proper relative Path to the external tileset image from the tmx location. (That's Done)

-> Fixing the crash where you have a map with more than 1 tilesets, because it can't find the proper TilesetRegion because of the FirstGID not being saved properly I think. (All this comes from Monogame.extended I believe)

**Comment by Melon-Bread** [comment]
So dumb question: If I want to use the current Tmx loader what version of tiled should I use or what features are added to the spec that I should avoid that prevent the tilemap from loading?

**Comment by prime31** [comment]
I use the latest version of Tiled. There arent any features that would keep a map from loading. There are some things that are not implemented/ignored such as offsets but all the important stuff (tiles, animated tiles, custom properties, etc) are all implemented.

**Comment by witlock** [comment]
Last I tried importing a tileset with type **collection of images** to place some images not following the grid I got a null reference exception.
These tilesets are currently not implemented, correct?

**Comment by prime31** [comment]
@witlock, that is correct. Collection of images in Tiled is currently a per image system with no atlassing. That means one draw call for every image which is pretty terrible. I didn't even bother spending the time to implement it because of that.

Some possible solutions:

1. If you just need random image placement Overlap2D is great. It automatically atlases all your images for you. This obviously won't work for you if you also need the tile map as well.

2. Add support for collections and send over a pull request ;)


There is one way this could possibly work but I'll have to do some thinking to decide if it will be easy/clear enough. By combining Tileds image collections with the texture packer Nez already has this could potentially work. The pipeline importer would have to pack the texture atlas (which means all images need to be in the same folder) and then it would need to somehow link that up to the Tiled data.

**Comment by prime31** [comment]
Alright, added basic support for image collections. Texture atlases are created on import automatically. It will only work for non-rotated images that have a height that is a multiple of the tile height for now.

36e01d05f7085093fde0c7902d98d2b3c6d21551
