### ISSUE TITLE
boxcastBroadphase giving erroneous minimumTranslationVectors on slopes

### ISSUE THREAD

**Issue by piedoom** [prime31/Nez#65]
I have a basic character controller set up, and I'm importing some non-rectangular collision polygons from a tiled map.   

When the player character moves, I have a boxcast set up to correct any intersections (like in the platformer example in Nez.Samples).

Here's a sample of the code I'm working with -

```
......

entity.colliders.unregisterAllCollidersWithPhysicsSystem();

....

foreach (var neighbor in neighbors)
                {
                    if (neighbor.isTrigger)
                        continue;

                    if (collider.collidesWith(neighbor, velocity, out collisionResult))
                    {
                            velocity -= collisionResult.minimumTranslationVector;
                        }

                        Debug.log($"translationvector: {collisionResult.minimumTranslationVector.X}, {collisionResult.minimumTranslationVector.Y}");
                    }
                }

...

```

On certain areas, this works correctly.  On flat ground, I might get a `log` output of `0, -0.4`, which makes sense as the player's gravity is pushing down at `0.4`.

However, on slopes, I'm getting some erratic readings - the character jumps all around and I get output such as 

```
Log: translationvector: 0, -31.58746
Log: translationvector: 0, 0.4125366
Log: translationvector: 0, -32.00002
Log: translationvector: 0, 32.4158
Log: translationvector: 0, -31.58228
Log: translationvector: 0, 0.4177246
Log: translationvector: 0, 32.41754
```

It's worth noting that my player character has a size of 32px, so there may be a relation between the jumps in `Y` being ~32

I've stripped everything off of my character besides the boxcast to make sure it was the issue, and it still remains unfortunately.

**Comment by prime31** [comment]
First off, you weren't supposed to find the platformer sample! It's just a skeleton and not done yet!

There are a couple things to be aware of with Separating Axis Theorem (SAT) which Nez uses for some collisions under the hood (such as Polygon). When SAT resolves a collision it will push the colliding object out in the shortest possible path. That can result in less than desireable results in some cases. There are some strategies to combat this:

- break up movement into multiple steps. Instead of moving `motion` move `motion / 2f` twice. That will reduce penetration and result in better MTVs. You will want to experiment with the maximum motion that you move to find a nice balance.
- to combat unwanted horizontal movement (you will see this when motionless on a slope with just gravity affecting the player), when you get back your collision result use `collisionResult. removeHorizontalTranslation`. That will rejigger the MTV to be vertical or in the direction of horizontal motion only.
- if you are using a Tiled Map skip SAT altogether and use the TileMapMover


All that being said, your results look a bit odd. It almost looks like the collision is being resolved inverted there. For example, an A -> B collision and a B -> A collision have the MTV calculated inversed for the second case. If you log the full result (`Debug.log( $"{collisionResult}")`) it will have the normal as well which could be useful in determining what is going on here.

**Comment by piedoom** [comment]
Didn't know about the TiledMapMover!  That saves a ton of headache.  I'll look into your implementation as well and see what I can learn.

**Comment by prime31** [comment]
Make sure you read the comment at the top of the file. It has the details on how to tag your tiles in Tiled for slopes and one way platforms.

**Comment by piedoom** [comment]
Hmm - I switched to the `TiledMapMover`, and got rid of everything I had before save basic movement controls.  It looks as if I'm still having the problem, even without doing a `boxcast`.

Here's a video of what's happening.  (I know the tile is square - didn't put in the effort to make a fancy nice sloped platform)

https://vid.me/doDp

I followed the guide in `TiledMapMover` and added custom properties to the tiles in Tiled - 
For the green tile, it has `nez:isSlope`, `nez:slopeTopLeft` = 32, and `nez:slopeTopRight` = 0 (from my understanding that is a slope up from left to right).

I can't see how I could be doing this on my end (although I'm sure it's more than possible!) - Here's my basic initialization.

```
// initialize our player
            var player = createEntity("player");
            var texture = content.Load<Texture2D>("Sprites/Player/PlayerTest");
            var sprite = new Sprite(texture);
            player.addComponent(sprite);

            var collider = player.addCollider(new BoxCollider());
            player.addComponent<TiledMapMover>(new TiledMapMover(tiledMapComponent.collisionLayer));

            player.addComponent<TiledPlayer>(new TiledPlayer());

            var followCamera = camera.entity.addComponent<FollowCamera>(new FollowCamera(player));
```

**Comment by prime31** [comment]
Is it possible the tiles are 16 pixels high? If so, try using 15 as the value for the low side and 0 for the high side.

**Comment by piedoom** [comment]
I just checked, Tiles are 32px square.  The issue still exists with the values `31` and `1`  - `15` and `0` does the same thing except with half height.  It also seems like the collisions for the block are stretched/offset by some amount.  I do, however, get a somewhat correct movement when the slope is very minimal with values like `4` and `0`.

**Comment by prime31** [comment]
Odd. Can you send over the project you are using to test with?

**Comment by piedoom** [comment]
Sure - https://file.io/gqx0eg

**Comment by prime31** [comment]
Looks like the link is 404ing.

**Comment by piedoom** [comment]
Oops, sorry.  Updated the link.

**Comment by prime31** [comment]
That monstrous commit should fix things up. I'm still not sure why this bug shows up for 32px tiles but not for 16px tiles (which is what I have been using). Odd one!

**Comment by piedoom** [comment]
I still seem to be having some issues with collisions - it's not spazzing out like the video I posted above, but slopes still seem to start and end in incorrect positions when I set the values to `0` and `32` (or `1` and `31`).  I was able to position the tile to what visually appears to be the correct position by using `16` and `-16`.  However, descending the slope does not work properly and the character is bumped up before started the descent (that's not me jumping!)

https://vid.me/9V3k

**Comment by prime31** [comment]
The TiledMapMover is 100% different than boxcast. It doesnt use the physics system at all. It gets all collision data querying the TiledMap directly.

I set the slope values to 0 and 31 to match what a normal 45 degree tile would be and it seems to be looking good: https://vid.me/410B

Note that I adjusted the TiledMapMover.colliderHorizontalInset and colliderVerticalInset to about 4 and 8. Depending on the slopes that you support you'll want to play with those values. 45 slopes are pretty steep so you can reduce them if you only have 22 and 11 slopes (more common scenario).

**Comment by piedoom** [comment]
Taken from the video you shared, it looks like the character is intersecting in places I would except.  Is this intended behaviour?  

Here's a really beautiful paint picture illustrating what I mean.

![untitled](https://cloud.githubusercontent.com/assets/8846211/16892652/5b77b1a6-4ae8-11e6-9426-6b1e7146663a.png)

**Comment by prime31** [comment]
That is indeed the intended effect. When in a slope tile the center of the collider is used for collisions. Any non-slope collisions use the entire edge in the direction of movement.

If that isn't the desired effect you can modify the code to use the front-most point as the perpendicular frontier and you'll then get no penetration at all if that is what you want.

**Comment by prime31** [comment]
I also just realized why I hadn't found the bug previously: the collision system is optimized for colliders that are less than 1 tile in width. Anything greater than 1 tile will probably work perfectly for everything except slopes, which would need some special care. I'll
Have to note that when it gets documented.

**Comment by piedoom** [comment]
Hopefully I'm not beating a dead horse here but I just can't seem to debug my initial issue (the one where I was using the physics system and SAT and colliders and all that jazz)

I've tried to rule out any variables by making two identical rectangular colliders - the one on the left is a PolygonCollider, the one on the right is a BoxCollider. Both are identical in shape, the only thing different is the type.

https://vid.me/UkG7

It's possible that I'm misunderstanding how this stuff works (and I apologize for that and thank you for your patience!) but it just doesn't seem normal to me.

It seems as though the bottom and right edges of the polygon collider work correctly, but the other two do not.

**Comment by prime31** [comment]
Send over a little repro Scene and I'll give it a look.

Side note: polygons and boxes are identical in just about every way internally. They are just tagged as a Box so that some things can be skipped as an optimization.

**Comment by piedoom** [comment]
I'll be out today so In the meantime [here's the full project ](https://drive.google.com/file/d/0B1hKuk3gVsYnTmlCZzl6bU9wTGs/view?usp=sharing)if that's helpful.  I'll send over a repro scene later tonight/tomorrow when I have the time.

I'm wondering if perhaps the polygon collider is having trouble figuring out how to be convex?  I have more of a background in 3D than 2D so this might not apply but maybe the "normals" of the top and left side are flipped creating weird collision problems.

![](http://i.imgur.com/9eEcRgC.jpg)

**Comment by prime31** [comment]
So, it looks like you have some Polygons here that arent centered. Their origin is a few miles away from their verts like so:

<img width="1097" alt="screen shot 2016-07-16 at 2 26 35 pm" src="https://cloud.githubusercontent.com/assets/60377/16897284/5e80334a-4b61-11e6-8b7b-02278710f38d.png">

That causes the normals to be calculated incorrectly for any collisions on the left/top due to the algorithm expecting the origin to be the center of the polygon. I can probably add some defensive code to work around this particular scenario but it would be adding extra calculations to a performance critical section of code so it probably wont happen.

A much better and more performant option is to just pre-calculate the verts centered around the polygon center. I added a helper method for this (`Polygon.findPolygonCenter`) and you can see below how it can be used to wrangle those verts so that they are hovering around the polygon origin instead of a few miles east of the origin:

```csharp
			foreach( var obj in tiledMap.getObjectGroup( "Collisions" ).objects )
			{
				var center = Polygon.findPolygonCenter( obj.polyPoints );
				var entity = createEntity( "poly-col" );
				entity.transform.setPosition( center );

				for( var i = 0; i < obj.polyPoints.Length; i++ )
					obj.polyPoints[i] -= center;
				
				entity.addCollider( new PolygonCollider( obj.polyPoints ) );
			}
```

On a side note, I made a couple minor mods to the BoxController2D script. You can see the diff [here](https://gist.github.com/prime31/d6134714de36fca1302da007c6280641/revisions).
