### ISSUE TITLE
UI Best practices tutorial request

### ISSUE THREAD

**Issue by piedoom** [prime31/Nez#69]
Hi,
I was wondering if you would be interested in making a little tutorial on UI best practices.  I've been looking through samples and the Nez inspector class to get an idea of how to best implement UI.  I've successfully created UI elements, but they're kind of messy and putting a bunch of view stuff in the Scene class seems wrong.

From looking at the Inspector class, it looks like it can be called nicely like `new Inspector(new Entity())` since it's not a component.  I tried implementing something similar to the inspector but It's not working out.
Thanks.

**Comment by prime31** [comment]
There will definitely be some more documentation/examples for creating UI coming in the future. For now, the libGDX or TableLayout documentation is the best place to get into the details of UI. Nez UI is pretty much an API compatible port of them.

On a very high level and in brief this is what I personally do for UI:

- add a ScreenSpaceRenderer to the Scene for the UI so that it gets rendered in screen space instead of in the Scene's camera space
- create a new Entity to house the UI
- add a UICanvas component and add it to the ScreenSpaceRenderer renderLayer
- create my UI in a Table for easy layout
- add the Table to the UICanvas.stage

**Comment by piedoom** [comment]
Great!  [I came up with a much cleaner solution thanks to your points](https://gist.github.com/piedoom/7c49097b1bf0eb59b1c4fc8bcfd4a7dc) - I'll link it in case anyone runs into a similar situation.

example usage class:

```
class DialogueBar : BaseUI{

    public DialogueBar(int renderLayer) : base(renderLayer){}

    protected override void Setup(){
        SetBackgroundColor(new Color(60,60,60));
    }

    protected override void PositionElements()
    {
        var targetHeight = Screen.height / 3;
        table.setBounds(0, Screen.height - targetHeight, Screen.width, targetHeight );
    }
}
```

**Comment by prime31** [comment]
That looks good to me. Should be a nice base to build on.
