### ISSUE TITLE
Mover component fails at high speeds

### ISSUE THREAD

**Issue by SharpenedSpoon** [prime31/Nez#8]
When trying to move at relatively high velocities, the Mover.move() method fails. I realize that at a certain point extra code needs to be written (with, say, extra linecast checks) to compensate for extremely high velocities, but while starting on a platformer with gravity, I was surprised to find that it failed fairly quickly, thought I'd bring it to your attention.

Steps to reproduce:
* Create a simple "player move" component (and entity of course) with gravity applied (but never zero'ed out when grounded)
* Create a ground whose boxcollider has a height of 10
* Once the player's y velocity exceeds 15, the player falls through the floor.

(The values above are, of course, not the only ones that will trigger this bug, but those happen to be the ones in the code samples)

-----

Here is a minimal code sample I whipped up real quick. I would include a zip of the project, but I know that you develop primarily on OSX and I'm on a PC right now, so I figured this might be easier.
```
// Game.cs
using Microsoft.Xna.Framework;
using Nez;

namespace Game2Test {
	public class Game1 : Core {

		public Game1() : base(width: 640, height: 480, isFullScreen: false, enableEntitySystems: false) {
		}
		
		protected override void Initialize() {
			base.Initialize();
			Core.debugRenderEnabled = true;
			var myScene = Scene.createWithDefaultRenderer(Color.Black);

			var player = myScene.addEntity(new Entity("player"));
			player.transform.position = new Vector2(50, 150);
			player.colliders.add<BoxCollider>(new BoxCollider(25, 25));
			player.addComponent<Mover>(new Mover());
			player.addComponent<PlayerMove>(new PlayerMove());


			var ground = myScene.addEntity(new Entity("ground"));
			ground.transform.position = new Vector2(0, 300);
			ground.colliders.add<BoxCollider>(new BoxCollider(640, 10));

			scene = myScene;
		}
	}
}
```

```
// PlayerMove.cs
using Nez;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Input;

namespace Game2Test {
	class PlayerMove : Component, IUpdatable {

		float speed = 100f;

		Vector2 velocity;

		public void update() {
			if (Input.isKeyDown(Keys.Left)) {
				velocity.X = -1 * speed;
			} else if (Input.isKeyDown(Keys.Right)) {
				velocity.X = speed;
			} else {
				velocity.X = 0f;
			}

			// apply gravity
			velocity.Y += Physics.gravity.Y * Time.deltaTime;

			Vector2 deltaMovement = velocity * Time.deltaTime;

			Debug.log("deltaMovement.Y = {0} and position.y = {1}", deltaMovement.Y, entity.transform.position.Y);

			CollisionResult collisionResult;
			entity.getComponent<Mover>().move(deltaMovement, out collisionResult);
		}
	}
}
```

**Comment by prime31** [comment]
The Mover is intended as an example of how to use the physics system with a multi-collider, multi-trigger setup, not an all-encompassing solution. If you want to use the Mover out of the box one stipulation is that your per frame movement must never exceed the half width of your Mover and your smallest obstacle. In your example you have a 25px player and a 10px ground so you don't have too much wiggle room since they are pretty small/thin objects.

Possible solutions:

- call Mover.move multiple times in a frame with your deltaMovement cut into chunks
- use a couple raycasts in the direction of movement if it is a large deltaMovement
- (if you are only using BoxColliders) use [ShapeCollisions.boxToBoxCast](https://github.com/prime31/Nez/blob/master/Nez-PCL/Physics/Shapes/ShapeCollisions.cs#L39) which is basically a raycast but with your players full BoxCollider instead of just a line.
- thicken walls/floors/ceilings (most likely a non-solution though depending on the game details)

The specifics of how to handle it will depend entirely on the specifics of your game.

In the future, a FastMover component will be doable that will rely on swept collision checks. The code is not yet complete for all of the possible combinations so this stuff isnt quite ready. There are several swept checks in the BETA namespace [here](https://github.com/prime31/Nez/blob/master/Nez-PCL/Physics/Shapes/RealtimeCollisions.cs) and swept poly-to-poly/box-to-box is [here](https://github.com/prime31/Nez/blob/master/Nez-PCL/Physics/Shapes/ShapeCollisions.cs). Notably absent is circleToBox (not yet complete) and circleToPoly.
