### ISSUE TITLE
High CPU usage when window is not focused

### ISSUE THREAD

**Issue by Scellow** [prime31/Nez#95]
Hello

When the window is focused, CPU usage is normal ~5%

But when the window is not focused anymore the CPU usage reach 30+%

Here is a gif: https://gfycat.com/DishonestDisguisedDamselfly

**Comment by prime31** [comment]
Nez doesn't actually do anything when it is backgrounded. It early outs on both Update and Draw (just using the last render). What you are seeing is an uncapped frame rate going through the roof. On Mac where things are capped at 60 fps you won't see that behavior. Just cap your framerate to something reasonable and it should take care of it or you could even just drop the framerate down to a really low number while backgrounded to curb the CPU even more.

**Comment by Scellow** [comment]
Setting ``IsFixedTimeStep`` to true solved the issue, but that's still weird, hight cpu when not active; and low cpu when active

**Comment by prime31** [comment]
I've never looked into it in detail on windows, but my guess is the following is happening: MonoGame is trying to render as many frames as possible but there is no rendering happening since Nez is using the previous render when in the background so it ends up ramping up the CPU like crazy. With next to no GPU action occurring it just spins its wheels on updated.
