### ISSUE TITLE
Suggestion: Ability to load assets without the Content Pipeline

### ISSUE THREAD

**Issue by Scellow** [prime31/Nez#96]
Hello

Pre processing assets only makes sense when your game is ready for release, your customers will have reduced loading time

But in the process of making a game, prototyping etc, when your assets needs to be edited a lot of time, the content pipeline is just an annoying thing and makes simple editing a real pain, having to rebuilt again and again for simple changes is annoying

Would be cool to have a feature to load and process raw assets as we want, just like libGDX

**Comment by prime31** [comment]
This isn't something I would ever add to Nez. There is nothing stopping you from adding it yourself though. The content pipeline process is so smooth these days there is just no reason to write every pipeline importer twice. Once you add a file to the pipeline tool you never need to think about it again or even open the pipeline tool again. When you build your game the pipeline tool will automatically rebuild assets that have changed. It just seems like that is more than sufficient rather than having code duplicated all over the place and adding extra dependencies to the runtime that don't really need to be there.

**Comment by piedoom** [comment]
Correct me if I'm wrong, but isn't there nothing stopping someone from doing this in the first place?  I thought monogame provided both strategies.

**Comment by prime31** [comment]
Absolutely. MonoGame imposes no resctrictions. Nez just chooses to use the pipeline for efficiency. It's far faster to load up already optimized structures vs having to parse JSON/XML/text at runtime. The pipeline in 3.5+ also auto builds everything so once you add content to it you never need to open it again. Doing it this way keeps all the extra libs (JSON, GZIP, etc) only in the pipeline so they aren't needed at runtime.

**Comment by Scellow** [comment]
I can understand your point of view, but in my case i need to be able to import assets without having to compile them (for modding, and testing purpose), i'll just try to make importer based on the exisint ones :p

**Comment by Scellow** [comment]
Also @prime31  do you plan to make a 3D renderer for models/meshes etc ?

**Comment by prime31** [comment]
Aha. Modding is a whole other ballgame. No way to avoid runtime parsing there. If you start with what's in the pipeline project already you should have a good jump start.

There are no plans to add 3D to Nez. It uses an orthographic camera for everything so it would require a ton of changes to get 3D in there. That being said there is already a Mesh class for constructing meshes at runtime. It doesn't impose any restrictions so technically it can be fed any verts that you want. You would just need to render it with a non-orthographic projection.
